[project]
name = "all"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.9",
    "more-itertools>=10.5.0",
    "tqdm>=4.66.5",
]

[tool.uv.workspace]
members = ["simple-uv"]
